- [ ] does gp work better than rf?
  -  with special uncertainty est? -- no, not today
- [X] use CB infill? no, seems to perform worse in experiments
- [X] does the surrogate model work with dependencies?
- [X] what does intermbo actually do? with RF model and with GP model
  - seems so, things just kinda suck
- [ ] what is the uncertainty of evals?
- [X] other infill crit?
- [X] multipoint proposal?
  - parallelization is difficult, we're going to work with the old system
- [X] acceleration?
  - doesn't seem to be feasible or profitable

* runs:
- mbo rf
- mbo gp
- random search
- replicates
* continuing
- [X] build sampler
- [X] check sampler works
- [X] finish bohb learner
- [X] check bohb learner works
- [X] reconstruct hb, bohb
- [ ] check these work and look as they should
- [X] write mbo for abs regret
- [X] write mbo for different & conditioned search spaces
- [X] write mbo script for different eval subsets
- [X] re-setup surrogates
- [ ] expand mbo run script for large scale
- [ ] run optimization
* experiments

 - infill: rs, vario, all
 - batch: smashy, hb
 -



 - batch smashy, infill all, my vary
 - batch hb, infill all, my vary
 -

 options: -o -M -S -B -I

 -o:  lcbench, rbv2_super, all
<times>



 -B smashy -I all   -M 0
 -B smashy -I all   -M 32 -b 960
 -B hb     -I all   -M 0
 -B smashy -I all   -M 0         -S
 -B smashy -I all   -M 32 -b 960 -S
 -B hb     -I all   -M 0         -S



# wyoming
Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 30  -M 0  -B smashy -I rs     -f run_0000000_lcbench_m0__smashy_rsinfill_______.rds
Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 30  -M 0  -B hb     -I rs     -f run_0000000_lcbench_m0__hb_____rsinfill_______.rds
Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 960 -M 32 -B smashy -I rs     -f run_0000000_lcbench_m32_smashy_rsinfill_______.rds

Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 30  -M 0  -B smashy -I rs  -S -f run_0000000_lcbench_m0__smashy_rsinfill__siman.rds
Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 30  -M 0  -B hb     -I rs  -S -f run_0000000_lcbench_m0__hb_____rsinfill__siman.rds
Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 960 -M 32 -B smashy -I rs  -S -f run_0000000_lcbench_m32_smashy_rsinfill__siman.rds




Rscript prepare_mbo.R -s 0000000 -o all        -b 30  -M 0  -B smashy -I all -S -f run_0000000_all_____m0__smashy_allinfill_siman.rds  # gx
Rscript prepare_mbo.R -s 0000000 -o all        -b 30  -M 0  -B hb     -I all -S -f run_0000000_all_____m0__hb_____allinfill_siman.rds  # px
Rscript prepare_mbo.R -s 0000000 -o all        -b 960 -M 32 -B smashy -I all -S -f run_0000000_all_____m32_smashy_allinfill_siman.rds  # wx  






Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 30  -M 0  -B smashy -I all    -f run_0000000_lcbench_m0__smashy_allinfill______.rds
Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 30  -M 0  -B hb     -I all    -f run_0000000_lcbench_m0__hb_____allinfill______.rds
Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 960 -M 32 -B smashy -I all    -f run_0000000_lcbench_m32_smashy_allinfill______.rds


Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 30  -M 0  -B smashy -I all -S -f run_0000000_lcbench_m0__smashy_allinfill_siman.rds
Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 30  -M 0  -B hb     -I all -S -f run_0000000_lcbench_m0__hb_____allinfill_siman.rds
Rscript prepare_mbo.R -s 0000000 -o lcbench    -b 960 -M 32 -B smashy -I all -S -f run_0000000_lcbench_m32_smashy_allinfill_siman.rds


Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 30  -M 0  -B smashy -I all    -f run_0000000_rbv2sup_m0__smashy_allinfill______.rds
Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 30  -M 0  -B hb     -I all    -f run_0000000_rbv2sup_m0__hb_____allinfill______.rds
Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 960 -M 32 -B smashy -I all    -f run_0000000_rbv2sup_m32_smashy_allinfill______.rds

Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 30  -M 0  -B smashy -I rs     -f run_0000000_rbv2sup_m0__smashy_rsinfill_______.rds
Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 30  -M 0  -B hb     -I rs     -f run_0000000_rbv2sup_m0__hb_____rsinfill_______.rds
Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 960 -M 32 -B smashy -I rs     -f run_0000000_rbv2sup_m32_smashy_rsinfill_______.rds

Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 30  -M 0  -B smashy -I all -S -f run_0000000_rbv2sup_m0__smashy_allinfill_siman.rds
Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 30  -M 0  -B hb     -I all -S -f run_0000000_rbv2sup_m0__hb_____allinfill_siman.rds
Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 960 -M 32 -B smashy -I all -S -f run_0000000_rbv2sup_m32_smashy_allinfill_siman.rds

Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 30  -M 0  -B smashy -I rs  -S -f run_0000000_rbv2sup_m0__smashy_rsinfill__siman.rds
Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 30  -M 0  -B hb     -I rs  -S -f run_0000000_rbv2sup_m0__hb_____rsinfill__siman.rds
Rscript prepare_mbo.R -s 0000000 -o rbv2_super -b 960 -M 32 -B smashy -I rs  -S -f run_0000000_rbv2sup_m32_smashy_rsinfill__siman.rds






Rscript prepare_mbo.R -s 0000000 -o all        -b 30  -M 0  -B smashy -I all    -f run_0000000_all_____m0__smashy_allinfill______.rds
Rscript prepare_mbo.R -s 0000000 -o all        -b 30  -M 0  -B hb     -I all    -f run_0000000_all_____m0__hb_____allinfill______.rds
Rscript prepare_mbo.R -s 0000000 -o all        -b 960 -M 32 -B smashy -I all    -f run_0000000_all_____m32_smashy_allinfill______.rds

Rscript prepare_mbo.R -s 0000000 -o all        -b 30  -M 0  -B smashy -I rs     -f run_0000000_all_____m0__smashy_rsinfill_______.rds
Rscript prepare_mbo.R -s 0000000 -o all        -b 30  -M 0  -B hb     -I rs     -f run_0000000_all_____m0__hb_____rsinfill_______.rds
Rscript prepare_mbo.R -s 0000000 -o all        -b 960 -M 32 -B smashy -I rs     -f run_0000000_all_____m32_smashy_rsinfill_______.rds

Rscript prepare_mbo.R -s 0000000 -o all        -b 30  -M 0  -B smashy -I all -S -f run_0000000_all_____m0__smashy_allinfill_siman.rds
Rscript prepare_mbo.R -s 0000000 -o all        -b 30  -M 0  -B hb     -I all -S -f run_0000000_all_____m0__hb_____allinfill_siman.rds
Rscript prepare_mbo.R -s 0000000 -o all        -b 960 -M 32 -B smashy -I all -S -f run_0000000_all_____m32_smashy_allinfill_siman.rds

Rscript prepare_mbo.R -s 0000000 -o all        -b 30  -M 0  -B smashy -I rs  -S -f run_0000000_all_____m0__smashy_rsinfill__siman.rds
Rscript prepare_mbo.R -s 0000000 -o all        -b 30  -M 0  -B hb     -I rs  -S -f run_0000000_all_____m0__hb_____rsinfill__siman.rds
Rscript prepare_mbo.R -s 0000000 -o all        -b 960 -M 32 -B smashy -I rs  -S -f run_0000000_all_____m32_smashy_rsinfill__siman.rds



