#' @title Terminator that Counts OptimizerMies Generations
#'
#' @name mlr_terminators_gens
#'
#' @description
#' [`Terminator`][bbotk::Terminator] that terminates after a given number of generations have passed in [`OptimizerMies`].
#'
#' If [`OptimizerMies`] is started on an archive that already has evaluated configurations, these evaluations count as
#' generation 0. If an initial, randomly sampled generation is generated by [`OptimizerMies`], it has generation number 1.
#' Setting `generation` to 1 therefore terminates after the evaluation of the initial sample, *unless* no initial sample is
#' generated by [`OptimizerMies`] and instead found in the archive. `generation` set to 0 avoids any evaluation within [`OptimizerMies`]
#' (but is ignored if no `dob` column is in the archive).
#'
#' When doing multi-fidelity optimization, and fidelity of a configuration is increased because of a step in the fidelity schedule,
#' or because they were sampled new and survived, then this fidelity refinement happens as part of an already started generation. This means
#' termination at this fidelity refinement step is avoided.
#'
#' @section Dictionary:
#' This [`Terminator`][bbotk::Terminator] can be created with the short access form [`trm()`][bbotk::trm] ([`trms()`][bbotk::trm] to get a list),
#' or through the [dictionary][mlr3misc::Dictionary] [`mlr_terminators`][bbotk::mlr_terminators] in the following way:
#'
#' ```
#' # preferred
#' trm("gens")
#' trms("gens")  # takes vector IDs, returns list of Terminators
#'
#' # long form
#' mlr_terminators$get("gens")
#' ```
#'
#' @section Hyperparameters:
#' * `generations` :: `integer(1)`\cr
#'   Number of generations to evaluate, after which to stop. Initialized to `Inf`.
#'
#' @examples
#' trm("gens", generations = 10)
#' @export
TerminatorGenerations = R6Class("TerminatorGenerations", inherit = Terminator,
  public = list(
    #' @description
    #' Initialize the `TerminatorGenerations` object.
    initialize = function() {
      param_set = ps(generations = p_int(0, special_vals = list(Inf), tags = "required"))
      param_set$values$generations = Inf
      super$initialize(param_set = param_set, properties = c("single-crit", "multi-crit"))
      self$unit = "generations"
    },

    #' @description
    #' Is `TRUE` if when the termination criterion is matched, `FALSE` otherwise.
    #' @return `logical(1)`: Whether to terminate.
    is_terminated = function(archive) {
      max(archive$data$dob, 0) >= self$param_set$get_values()$generations
    }
  ),

  private = list(
    .status = function(archive) {
      c(
        max_steps = self$param_set$get_values()$generations,
        current_steps = max(archive$data$dob, 0)
      )
    }
  )
)
